### ISSUE TITLE
publish npm package

### ISSUE THREAD

**Issue by jolestar** [movefuns/move-js#2]

**Comment by yubing744** [comment]
@jolestar Can you configure the secret of npm access tokens in the repository so I can publish via https://github.com/marketplace/actions/npm-publish? You should be able to find npm access tokens in the secret at https://github.com/starcoinorg/starcoin.js.

**Comment by jolestar** [comment]
> @jolestar Can you configure the secret of npm access tokens in the repository so I can publish via https://github.com/marketplace/actions/npm-publish? You should be able to find npm access tokens in the secret at https://github.com/starcoinorg/starcoin.js.

@wk3368 please help config, I can not find the secret at starcoin.js.

**Comment by wk3368** [comment]
@yubing744  give me your npm account email, then I can invite you into the npm organization: starcoin
then you can npm login and publish by yourself.
PS： you need to change the name in the package.json:

"name": "@yubing744/move-js",

to 

"name": "@starcoin/move-js",

**Comment by yubing744** [comment]
> @yubing744 give me your npm account email, then I can invite you into the npm organization: starcoin then you can npm login and publish by yourself. PS： you need to change the name in the package.json:
> 
> "name": "@yubing744/move-js",
> 
> to
> 
> "name": "@starcoin/move-js",

my npm account email is yubing744@163.com

**Comment by wk3368** [comment]
> yubing744@163.com

invited.
you can use this command `npm publish --access public --tag latest` to publish it  after `npm login`.

**Comment by yubing744** [comment]
> > [yubing744@163.com](mailto:yubing744@163.com)
> 
> invited. you can use this command `npm publish --access public --tag latest` to publish it after `npm login`.

OK

**Comment by yubing744** [comment]
@wk3368 I don't seem to have permission to publish npm packages to the starcoin org.

![image](https://user-images.githubusercontent.com/1449069/173172079-55ccc8ce-75e9-411e-b0dd-2a2dcc005713.png)
![image](https://user-images.githubusercontent.com/1449069/173172107-97897617-f9b9-4133-847b-1cc8c9cebb38.png)
![image](https://user-images.githubusercontent.com/1449069/173172120-06483080-3a73-4421-9e04-c9ef4dd28de8.png)

**Comment by yubing744** [comment]
@jolestar @wk3368 I think it is better to configure npm's access token in the secret of this repository.

**Comment by wk3368** [comment]
你的命令写错了 我给的是 --access public 不是--access=public

**Comment by jolestar** [comment]
@wk3368 give me a npm org invite, email: jolestar@gmail.com

**Comment by yubing744** [comment]
> @jolestar @wk3368 I think it is better to configure npm's access token in the secret of this repository.

I try it.

**Comment by yubing744** [comment]
@jolestar @wk3368 It's ok.   https://www.npmjs.com/package/@starcoin/move-js
